# Generated by Django 5.2.8 on 2025-11-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
