# Generated by Django 5.2.8 on 2025-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumeapp', '0003_remove_blogpost_image_blogpost_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
