# Generated by Django 5.2.8 on 2025-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumeapp', '0004_post_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_html',
        ),
        migrations.AddField(
            model_name='post',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
