# Generated by Django 5.2.8 on 2025-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumeapp', '0005_remove_post_content_html_post_content_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
    ]
